function plant = loadModel(bundleDir)
%LOADMODEL Load one generated soft-arm model bundle.
arguments
    bundleDir (1,1) string
end
bundleDir = string(java.io.File(bundleDir).getCanonicalPath());
manifestPath = fullfile(bundleDir, "manifest.json");
assert(isfile(manifestPath), "softarm:MissingManifest", ...
    "No manifest.json exists in %s", bundleDir);
manifest = jsondecode(fileread(manifestPath));
persistent activeBundle
if ~isempty(activeBundle) && activeBundle ~= bundleDir && isfolder(activeBundle) && ...
        contains(path, char(activeBundle), "IgnoreCase", true)
    rmpath(activeBundle);
end
clear softarm_mass softarm_bias softarm_kinematics softarm_end_jacobian ...
    softarm_forward_dynamics softarm_state_rhs softarm_actuator_coordinates ...
    softarm_actuator_jacobian softarm_actuator_velocity_bias ...
    softarm_actuator_force softarm_actuator_info softarm_actuator_acceleration
addpath(bundleDir, "-begin");
activeBundle = bundleDir;
defaults = reshape([manifest.parameters.default], [], 1);
plant = struct(...
    "bundle", bundleDir, ...
    "manifest", manifest, ...
    "nq", numel(manifest.coordinates), ...
    "parameters", defaults, ...
    "mass", @softarm_mass, ...
    "bias", @softarm_bias, ...
    "kinematics", @softarm_kinematics, ...
    "endJacobian", @softarm_end_jacobian, ...
    "forwardDynamics", @softarm_forward_dynamics, ...
    "stateRhs", @softarm_state_rhs);
if exist("softarm_actuator_info","file") == 2
    info = softarm_actuator_info();
    actuation = struct(...
        "names", info.names, ...
        "kinds", info.kinds, ...
        "count", info.count, ...
        "accelerationMode", info.acceleration, ...
        "coordinates", @softarm_actuator_coordinates, ...
        "jacobian", @softarm_actuator_jacobian, ...
        "velocityBias", @softarm_actuator_velocity_bias, ...
        "force", @softarm_actuator_force);
    if exist("softarm_actuator_acceleration","file") == 2
        actuation.acceleration = @softarm_actuator_acceleration;
    end
    plant.actuation = actuation;
else
    plant.actuation = [];
end
end
