function plant = loadModel(bundleDir)
%LOADMODEL Load one generated soft-arm model bundle.
arguments
    bundleDir (1,1) string
end
bundleDir = string(java.io.File(bundleDir).getCanonicalPath());
manifestPath = fullfile(bundleDir, "manifest.json");
assert(isfile(manifestPath), "softarm:MissingManifest", ...
    "No manifest.json exists in %s", bundleDir);
manifest = jsondecode(fileread(manifestPath));
persistent activeBundle
if ~isempty(activeBundle) && activeBundle ~= bundleDir && isfolder(activeBundle) && ...
        contains(path, char(activeBundle), "IgnoreCase", true)
    rmpath(activeBundle);
end
clear softarm_mass softarm_bias softarm_kinematics softarm_end_jacobian ...
    softarm_vehicle_wrench_map softarm_applied_force softarm_forward_dynamics ...
    softarm_state_rhs softarm_actuator_coordinates ...
    softarm_actuator_jacobian softarm_actuator_velocity_bias ...
    softarm_actuator_force softarm_actuator_acceleration ...
    softarm_constraint_value softarm_constraint_jacobian ...
    softarm_constraint_velocity_bias softarm_constraint_reaction_map ...
    softarm_constraint_stabilization softarm_constraint_acceleration
addpath(bundleDir, "-begin");
activeBundle = bundleDir;
defaults = reshape([manifest.parameters.default], [], 1);
if isempty(manifest.coordinates.base)
    baseCoordinates = {};
else
    baseCoordinates = cellstr(manifest.coordinates.base);
end
if isempty(manifest.coordinates.arm)
    armCoordinates = {};
else
    armCoordinates = cellstr(manifest.coordinates.arm);
end
plant = struct(...
    "bundle", bundleDir, ...
    "manifest", manifest, ...
    "nbase", numel(baseCoordinates), ...
    "narm", numel(armCoordinates), ...
    "nq", numel(baseCoordinates)+numel(armCoordinates), ...
    "parameters", defaults, ...
    "mass", @softarm_mass, ...
    "bias", @softarm_bias, ...
    "kinematics", @softarm_kinematics, ...
    "endJacobian", @softarm_end_jacobian, ...
    "appliedForce", @softarm_applied_force, ...
    "forwardDynamics", @softarm_forward_dynamics, ...
    "stateRhs", @softarm_state_rhs);
if ~isempty(manifest.actuation)
    channels = manifest.actuation.channels;
    actuation = struct(...
        "names", string({channels.name}), ...
        "kinds", string({channels.kind}), ...
        "count", numel(channels), ...
        "accelerationMode", string(manifest.actuation.acceleration), ...
        "coordinates", @softarm_actuator_coordinates, ...
        "jacobian", @softarm_actuator_jacobian, ...
        "velocityBias", @softarm_actuator_velocity_bias, ...
        "force", @softarm_actuator_force);
    if exist("softarm_actuator_acceleration","file") == 2
        actuation.acceleration = @softarm_actuator_acceleration;
    end
    plant.actuation = actuation;
else
    plant.actuation = [];
end
if ~isempty(manifest.constraint)
    channels = manifest.constraint.channels;
    constraint = struct(...
        "family", string(manifest.constraint.family), ...
        "names", string({channels.name}), ...
        "kinds", string({channels.kind}), ...
        "count", numel(channels), ...
        "value", @softarm_constraint_value, ...
        "jacobian", @softarm_constraint_jacobian, ...
        "velocityBias", @softarm_constraint_velocity_bias, ...
        "reactionMap", @softarm_constraint_reaction_map, ...
        "acceleration", @softarm_constraint_acceleration);
    plant.constraint = constraint;
else
    plant.constraint = [];
end
end
